"""LoRA compatibility preflight contracts: verdicts, reason codes, stages."""

from __future__ import annotations

# Reason codes (fail-closed refusal identifiers).
CANDIDATE_PIN_MISMATCH = "CANDIDATE_PIN_MISMATCH"
CANDIDATE_TENSOR_CENSUS_MISMATCH = "CANDIDATE_TENSOR_CENSUS_MISMATCH"
CANDIDATE_PROFILE_UNSUPPORTED = "CANDIDATE_PROFILE_UNSUPPORTED"
TARGET_MODULE_MAPPING_UNRESOLVED = "TARGET_MODULE_MAPPING_UNRESOLVED"
BASE_REPRESENTATION_UNBINDABLE = "BASE_REPRESENTATION_UNBINDABLE"
OFFLINE_FOLD_ORACLE_NOT_PASSED = "OFFLINE_FOLD_ORACLE_NOT_PASSED"

# Stage identifiers used in evidence.
STAGE_CANDIDATE_PIN = "candidate-pin"
STAGE_CANDIDATE_CENSUS = "candidate-census"
STAGE_CANDIDATE_PROFILE = "candidate-profile"
STAGE_TARGET_MAPPING = "target-mapping"
STAGE_BASE_REPRESENTATION = "base-representation"
STAGE_OFFLINE_ORACLE = "offline-fold-oracle"

__all__ = [
    "CANDIDATE_PIN_MISMATCH",
    "CANDIDATE_TENSOR_CENSUS_MISMATCH",
    "CANDIDATE_PROFILE_UNSUPPORTED",
    "TARGET_MODULE_MAPPING_UNRESOLVED",
    "BASE_REPRESENTATION_UNBINDABLE",
    "OFFLINE_FOLD_ORACLE_NOT_PASSED",
    "STAGE_CANDIDATE_PIN",
    "STAGE_CANDIDATE_CENSUS",
    "STAGE_CANDIDATE_PROFILE",
    "STAGE_TARGET_MAPPING",
    "STAGE_BASE_REPRESENTATION",
    "STAGE_OFFLINE_ORACLE",
]
